package com.managementsystem.guestroom.domain.platform;

// Generated 2012-11-5 15:25:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lists generated by hbm2java
 */
public class Lists implements java.io.Serializable {

	private String entryid;
	private Lists lists;
	private String listname;
	private String text;
	private String value;
	private Integer level;
	private Integer sortorder;
	private String definitionid;
	private String description;
	private Boolean systemlist;
	private String createdbyuserid;
	private Date createdondate;
	private String lastmodifiedbyuserId;
	private Date lastmodifiedondate;
	private Set listses = new HashSet(0);

	public Lists() {
	}

	public Lists(String entryid, String listname, String text, String value) {
		this.entryid = entryid;
		this.listname = listname;
		this.text = text;
		this.value = value;
	}

	public Lists(String entryid, Lists lists, String listname, String text,
			String value, Integer level, Integer sortorder,
			String definitionid, String description, Boolean systemlist,
			String createdbyuserid, Date createdondate,
			String lastmodifiedbyuserId, Date lastmodifiedondate, Set listses) {
		this.entryid = entryid;
		this.lists = lists;
		this.listname = listname;
		this.text = text;
		this.value = value;
		this.level = level;
		this.sortorder = sortorder;
		this.definitionid = definitionid;
		this.description = description;
		this.systemlist = systemlist;
		this.createdbyuserid = createdbyuserid;
		this.createdondate = createdondate;
		this.lastmodifiedbyuserId = lastmodifiedbyuserId;
		this.lastmodifiedondate = lastmodifiedondate;
		this.listses = listses;
	}

	public String getEntryid() {
		return this.entryid;
	}

	public void setEntryid(String entryid) {
		this.entryid = entryid;
	}

	public Lists getLists() {
		return this.lists;
	}

	public void setLists(Lists lists) {
		this.lists = lists;
	}

	public String getListname() {
		return this.listname;
	}

	public void setListname(String listname) {
		this.listname = listname;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Integer getSortorder() {
		return this.sortorder;
	}

	public void setSortorder(Integer sortorder) {
		this.sortorder = sortorder;
	}

	public String getDefinitionid() {
		return this.definitionid;
	}

	public void setDefinitionid(String definitionid) {
		this.definitionid = definitionid;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getSystemlist() {
		return this.systemlist;
	}

	public void setSystemlist(Boolean systemlist) {
		this.systemlist = systemlist;
	}

	public String getCreatedbyuserid() {
		return this.createdbyuserid;
	}

	public void setCreatedbyuserid(String createdbyuserid) {
		this.createdbyuserid = createdbyuserid;
	}

	public Date getCreatedondate() {
		return this.createdondate;
	}

	public void setCreatedondate(Date createdondate) {
		this.createdondate = createdondate;
	}

	public String getLastmodifiedbyuserId() {
		return this.lastmodifiedbyuserId;
	}

	public void setLastmodifiedbyuserId(String lastmodifiedbyuserId) {
		this.lastmodifiedbyuserId = lastmodifiedbyuserId;
	}

	public Date getLastmodifiedondate() {
		return this.lastmodifiedondate;
	}

	public void setLastmodifiedondate(Date lastmodifiedondate) {
		this.lastmodifiedondate = lastmodifiedondate;
	}

	public Set getListses() {
		return this.listses;
	}

	public void setListses(Set listses) {
		this.listses = listses;
	}

}
