package com.managementsystem.guestroom.domain.platform;

// Generated 2012-11-5 15:25:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Portalsettings generated by hbm2java
 */
public class Portalsettings implements java.io.Serializable {

	private PortalsettingsId id;
	private Portal portal;
	private String settingValue;
	private String cultureCode;
	private String createdbyuserid;
	private Date createdondate;
	private String lastmodifiedbyuserid;
	private Date lastmodifiedondate;

	public Portalsettings() {
	}

	public Portalsettings(PortalsettingsId id, Portal portal) {
		this.id = id;
		this.portal = portal;
	}

	public Portalsettings(PortalsettingsId id, Portal portal,
			String settingValue, String cultureCode, String createdbyuserid,
			Date createdondate, String lastmodifiedbyuserid,
			Date lastmodifiedondate) {
		this.id = id;
		this.portal = portal;
		this.settingValue = settingValue;
		this.cultureCode = cultureCode;
		this.createdbyuserid = createdbyuserid;
		this.createdondate = createdondate;
		this.lastmodifiedbyuserid = lastmodifiedbyuserid;
		this.lastmodifiedondate = lastmodifiedondate;
	}

	public PortalsettingsId getId() {
		return this.id;
	}

	public void setId(PortalsettingsId id) {
		this.id = id;
	}

	public Portal getPortal() {
		return this.portal;
	}

	public void setPortal(Portal portal) {
		this.portal = portal;
	}

	public String getSettingValue() {
		return this.settingValue;
	}

	public void setSettingValue(String settingValue) {
		this.settingValue = settingValue;
	}

	public String getCultureCode() {
		return this.cultureCode;
	}

	public void setCultureCode(String cultureCode) {
		this.cultureCode = cultureCode;
	}

	public String getCreatedbyuserid() {
		return this.createdbyuserid;
	}

	public void setCreatedbyuserid(String createdbyuserid) {
		this.createdbyuserid = createdbyuserid;
	}

	public Date getCreatedondate() {
		return this.createdondate;
	}

	public void setCreatedondate(Date createdondate) {
		this.createdondate = createdondate;
	}

	public String getLastmodifiedbyuserid() {
		return this.lastmodifiedbyuserid;
	}

	public void setLastmodifiedbyuserid(String lastmodifiedbyuserid) {
		this.lastmodifiedbyuserid = lastmodifiedbyuserid;
	}

	public Date getLastmodifiedondate() {
		return this.lastmodifiedondate;
	}

	public void setLastmodifiedondate(Date lastmodifiedondate) {
		this.lastmodifiedondate = lastmodifiedondate;
	}

}
