package com.managementsystem.guestroom.domain.platform;

// Generated 2012-11-5 15:25:52 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Shiftwork generated by hbm2java
 */
public class Shiftwork implements java.io.Serializable {

	private long shiftworkId;
	private User user;
	private Date workStarttime;
	private Date workEndtime;
	private Date createdOnDate;
	private String comment;

	public Shiftwork() {
	}

	public Shiftwork(long shiftworkId) {
		this.shiftworkId = shiftworkId;
	}

	public Shiftwork(long shiftworkId, User user, Date workStarttime,
			Date workEndtime, Date createdOnDate, String comment) {
		this.shiftworkId = shiftworkId;
		this.user = user;
		this.workStarttime = workStarttime;
		this.workEndtime = workEndtime;
		this.createdOnDate = createdOnDate;
		this.comment = comment;
	}

	public long getShiftworkId() {
		return this.shiftworkId;
	}

	public void setShiftworkId(long shiftworkId) {
		this.shiftworkId = shiftworkId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getWorkStarttime() {
		return this.workStarttime;
	}

	public void setWorkStarttime(Date workStarttime) {
		this.workStarttime = workStarttime;
	}

	public Date getWorkEndtime() {
		return this.workEndtime;
	}

	public void setWorkEndtime(Date workEndtime) {
		this.workEndtime = workEndtime;
	}

	public Date getCreatedOnDate() {
		return this.createdOnDate;
	}

	public void setCreatedOnDate(Date createdOnDate) {
		this.createdOnDate = createdOnDate;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
