package com.managementsystem.guestroom.domain.platform;

// Generated 2012-11-5 15:25:52 by Hibernate Tools 3.4.0.CR1

/**
 * PortalsettingsId generated by hbm2java
 */
public class PortalsettingsId implements java.io.Serializable {

	private String portalId;
	private String settingName;

	public PortalsettingsId() {
	}

	public PortalsettingsId(String portalId, String settingName) {
		this.portalId = portalId;
		this.settingName = settingName;
	}

	public String getPortalId() {
		return this.portalId;
	}

	public void setPortalId(String portalId) {
		this.portalId = portalId;
	}

	public String getSettingName() {
		return this.settingName;
	}

	public void setSettingName(String settingName) {
		this.settingName = settingName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PortalsettingsId))
			return false;
		PortalsettingsId castOther = (PortalsettingsId) other;

		return ((this.getPortalId() == castOther.getPortalId()) || (this
				.getPortalId() != null && castOther.getPortalId() != null && this
				.getPortalId().equals(castOther.getPortalId())))
				&& ((this.getSettingName() == castOther.getSettingName()) || (this
						.getSettingName() != null
						&& castOther.getSettingName() != null && this
						.getSettingName().equals(castOther.getSettingName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPortalId() == null ? 0 : this.getPortalId().hashCode());
		result = 37
				* result
				+ (getSettingName() == null ? 0 : this.getSettingName()
						.hashCode());
		return result;
	}

}
