package com.managementsystem.guestroom.domain.platform;

// Generated 2012-11-5 15:25:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String userId;
	private String userName;
	private String password;
	private String realname;
	private String description;
	private Integer status;
	private String lastipaddress;
	private Set roles = new HashSet(0);
	private Set shiftworks = new HashSet(0);

	public User() {
	}

	public User(String userId) {
		this.userId = userId;
	}

	public User(String userId, String userName, String password,
			String realname, String description, Integer status,
			String lastipaddress, Set roles, Set shiftworks) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.realname = realname;
		this.description = description;
		this.status = status;
		this.lastipaddress = lastipaddress;
		this.roles = roles;
		this.shiftworks = shiftworks;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getLastipaddress() {
		return this.lastipaddress;
	}

	public void setLastipaddress(String lastipaddress) {
		this.lastipaddress = lastipaddress;
	}

	public Set getRoles() {
		return this.roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

	public Set getShiftworks() {
		return this.shiftworks;
	}

	public void setShiftworks(Set shiftworks) {
		this.shiftworks = shiftworks;
	}

}
