package com.managementsystem.guestroom.domain.hibernate;

// Generated 2012-11-5 14:40:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Build generated by hbm2java
 */
public class Build implements java.io.Serializable {

	private String buildId;
	private Hotel hotel;
	private String buildName;
	private String buildAddress;
	private String buildComment;
	private Set floors = new HashSet(0);

	public Build() {
	}

	public Build(String buildId) {
		this.buildId = buildId;
	}

	public Build(String buildId, Hotel hotel, String buildName,
			String buildAddress, String buildComment, Set floors) {
		this.buildId = buildId;
		this.hotel = hotel;
		this.buildName = buildName;
		this.buildAddress = buildAddress;
		this.buildComment = buildComment;
		this.floors = floors;
	}

	public String getBuildId() {
		return this.buildId;
	}

	public void setBuildId(String buildId) {
		this.buildId = buildId;
	}

	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	public String getBuildName() {
		return this.buildName;
	}

	public void setBuildName(String buildName) {
		this.buildName = buildName;
	}

	public String getBuildAddress() {
		return this.buildAddress;
	}

	public void setBuildAddress(String buildAddress) {
		this.buildAddress = buildAddress;
	}

	public String getBuildComment() {
		return this.buildComment;
	}

	public void setBuildComment(String buildComment) {
		this.buildComment = buildComment;
	}

	public Set getFloors() {
		return this.floors;
	}

	public void setFloors(Set floors) {
		this.floors = floors;
	}

}
