package com.managementsystem.guestroom.domain.hibernate;

// Generated 2012-11-6 13:37:38 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel implements java.io.Serializable {

	private String hotelId;
	private District district;
	private String hotelName;
	private String hotelEnname;
	private String hotelAddress;
	private String hotelPhone;
	private String hotelFax;
	private String hotelDesc;
	private String hotelPhoto;
	private String hotelLong;
	private String hotelLat;
	private String hotelComment;
	private Set builds = new HashSet(0);
	private Set roomtypes = new HashSet(0);
	private Set departments = new HashSet(0);

	public Hotel() {
	}

	public Hotel(String hotelId) {
		this.hotelId = hotelId;
	}

	public Hotel(String hotelId, District district, String hotelName,
			String hotelEnname, String hotelAddress, String hotelPhone,
			String hotelFax, String hotelDesc, String hotelPhoto,
			String hotelLong, String hotelLat, String hotelComment, Set builds,
			Set roomtypes, Set departments) {
		this.hotelId = hotelId;
		this.district = district;
		this.hotelName = hotelName;
		this.hotelEnname = hotelEnname;
		this.hotelAddress = hotelAddress;
		this.hotelPhone = hotelPhone;
		this.hotelFax = hotelFax;
		this.hotelDesc = hotelDesc;
		this.hotelPhoto = hotelPhoto;
		this.hotelLong = hotelLong;
		this.hotelLat = hotelLat;
		this.hotelComment = hotelComment;
		this.builds = builds;
		this.roomtypes = roomtypes;
		this.departments = departments;
	}

	public String getHotelId() {
		return this.hotelId;
	}

	public void setHotelId(String hotelId) {
		this.hotelId = hotelId;
	}

	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	public String getHotelName() {
		return this.hotelName;
	}

	public void setHotelName(String hotelName) {
		this.hotelName = hotelName;
	}

	public String getHotelEnname() {
		return this.hotelEnname;
	}

	public void setHotelEnname(String hotelEnname) {
		this.hotelEnname = hotelEnname;
	}

	public String getHotelAddress() {
		return this.hotelAddress;
	}

	public void setHotelAddress(String hotelAddress) {
		this.hotelAddress = hotelAddress;
	}

	public String getHotelPhone() {
		return this.hotelPhone;
	}

	public void setHotelPhone(String hotelPhone) {
		this.hotelPhone = hotelPhone;
	}

	public String getHotelFax() {
		return this.hotelFax;
	}

	public void setHotelFax(String hotelFax) {
		this.hotelFax = hotelFax;
	}

	public String getHotelDesc() {
		return this.hotelDesc;
	}

	public void setHotelDesc(String hotelDesc) {
		this.hotelDesc = hotelDesc;
	}

	public String getHotelPhoto() {
		return this.hotelPhoto;
	}

	public void setHotelPhoto(String hotelPhoto) {
		this.hotelPhoto = hotelPhoto;
	}

	public String getHotelLong() {
		return this.hotelLong;
	}

	public void setHotelLong(String hotelLong) {
		this.hotelLong = hotelLong;
	}

	public String getHotelLat() {
		return this.hotelLat;
	}

	public void setHotelLat(String hotelLat) {
		this.hotelLat = hotelLat;
	}

	public String getHotelComment() {
		return this.hotelComment;
	}

	public void setHotelComment(String hotelComment) {
		this.hotelComment = hotelComment;
	}

	public Set getBuilds() {
		return this.builds;
	}

	public void setBuilds(Set builds) {
		this.builds = builds;
	}

	public Set getRoomtypes() {
		return this.roomtypes;
	}

	public void setRoomtypes(Set roomtypes) {
		this.roomtypes = roomtypes;
	}

	public Set getDepartments() {
		return this.departments;
	}

	public void setDepartments(Set departments) {
		this.departments = departments;
	}

}
