package com.managementsystem.guestroom.domain.hibernate;

// Generated 2012-11-5 14:40:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Prefsdefinedfield generated by hbm2java
 */
public class Prefsdefinedfield implements java.io.Serializable {

	private String definedfieldid;
	private Prefstype prefstype;
	private String fieldtitle;
	private Boolean visible;
	private Integer fieldorder;
	private String fieldtype;
	private Boolean required;
	private String defvalue;
	private String outputsettings;
	private String inputsettings;
	private String validationrule;
	private String validationmessage;
	private String helptext;
	private Boolean searchable;
	private Boolean showonedit;
	private Boolean privatefield;
	private String editstyle;
	private Set guestpreferences = new HashSet(0);

	public Prefsdefinedfield() {
	}

	public Prefsdefinedfield(String definedfieldid) {
		this.definedfieldid = definedfieldid;
	}

	public Prefsdefinedfield(String definedfieldid, Prefstype prefstype,
			String fieldtitle, Boolean visible, Integer fieldorder,
			String fieldtype, Boolean required, String defvalue,
			String outputsettings, String inputsettings, String validationrule,
			String validationmessage, String helptext, Boolean searchable,
			Boolean showonedit, Boolean privatefield, String editstyle,
			Set guestpreferences) {
		this.definedfieldid = definedfieldid;
		this.prefstype = prefstype;
		this.fieldtitle = fieldtitle;
		this.visible = visible;
		this.fieldorder = fieldorder;
		this.fieldtype = fieldtype;
		this.required = required;
		this.defvalue = defvalue;
		this.outputsettings = outputsettings;
		this.inputsettings = inputsettings;
		this.validationrule = validationrule;
		this.validationmessage = validationmessage;
		this.helptext = helptext;
		this.searchable = searchable;
		this.showonedit = showonedit;
		this.privatefield = privatefield;
		this.editstyle = editstyle;
		this.guestpreferences = guestpreferences;
	}

	public String getDefinedfieldid() {
		return this.definedfieldid;
	}

	public void setDefinedfieldid(String definedfieldid) {
		this.definedfieldid = definedfieldid;
	}

	public Prefstype getPrefstype() {
		return this.prefstype;
	}

	public void setPrefstype(Prefstype prefstype) {
		this.prefstype = prefstype;
	}

	public String getFieldtitle() {
		return this.fieldtitle;
	}

	public void setFieldtitle(String fieldtitle) {
		this.fieldtitle = fieldtitle;
	}

	public Boolean getVisible() {
		return this.visible;
	}

	public void setVisible(Boolean visible) {
		this.visible = visible;
	}

	public Integer getFieldorder() {
		return this.fieldorder;
	}

	public void setFieldorder(Integer fieldorder) {
		this.fieldorder = fieldorder;
	}

	public String getFieldtype() {
		return this.fieldtype;
	}

	public void setFieldtype(String fieldtype) {
		this.fieldtype = fieldtype;
	}

	public Boolean getRequired() {
		return this.required;
	}

	public void setRequired(Boolean required) {
		this.required = required;
	}

	public String getDefvalue() {
		return this.defvalue;
	}

	public void setDefvalue(String defvalue) {
		this.defvalue = defvalue;
	}

	public String getOutputsettings() {
		return this.outputsettings;
	}

	public void setOutputsettings(String outputsettings) {
		this.outputsettings = outputsettings;
	}

	public String getInputsettings() {
		return this.inputsettings;
	}

	public void setInputsettings(String inputsettings) {
		this.inputsettings = inputsettings;
	}

	public String getValidationrule() {
		return this.validationrule;
	}

	public void setValidationrule(String validationrule) {
		this.validationrule = validationrule;
	}

	public String getValidationmessage() {
		return this.validationmessage;
	}

	public void setValidationmessage(String validationmessage) {
		this.validationmessage = validationmessage;
	}

	public String getHelptext() {
		return this.helptext;
	}

	public void setHelptext(String helptext) {
		this.helptext = helptext;
	}

	public Boolean getSearchable() {
		return this.searchable;
	}

	public void setSearchable(Boolean searchable) {
		this.searchable = searchable;
	}

	public Boolean getShowonedit() {
		return this.showonedit;
	}

	public void setShowonedit(Boolean showonedit) {
		this.showonedit = showonedit;
	}

	public Boolean getPrivatefield() {
		return this.privatefield;
	}

	public void setPrivatefield(Boolean privatefield) {
		this.privatefield = privatefield;
	}

	public String getEditstyle() {
		return this.editstyle;
	}

	public void setEditstyle(String editstyle) {
		this.editstyle = editstyle;
	}

	public Set getGuestpreferences() {
		return this.guestpreferences;
	}

	public void setGuestpreferences(Set guestpreferences) {
		this.guestpreferences = guestpreferences;
	}

}
