package com.managementsystem.guestroom.domain.hibernate;

// Generated 2012-11-6 13:37:38 by Hibernate Tools 3.4.0.CR1

/**
 * Roomassignedgrouies generated by hbm2java
 */
public class Roomassignedgrouies implements java.io.Serializable {

	private String itemid;
	private Room room;
	private String roomgroupId;

	public Roomassignedgrouies() {
	}

	public Roomassignedgrouies(String itemid) {
		this.itemid = itemid;
	}

	public Roomassignedgrouies(String itemid, Room room, String roomgroupId) {
		this.itemid = itemid;
		this.room = room;
		this.roomgroupId = roomgroupId;
	}

	public String getItemid() {
		return this.itemid;
	}

	public void setItemid(String itemid) {
		this.itemid = itemid;
	}

	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	public String getRoomgroupId() {
		return this.roomgroupId;
	}

	public void setRoomgroupId(String roomgroupId) {
		this.roomgroupId = roomgroupId;
	}

}
