package com.managementsystem.guestroom.domain.hibernate;

// Generated 2012-11-5 14:40:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Roomtype generated by hbm2java
 */
public class Roomtype implements java.io.Serializable {

	private String roomtypeId;
	private Hotel hotel;
	private String roomtypeName;
	private String roomtypeTemplate;
	private Integer roomtypeMinguests;
	private Integer roomtypeMaxguests;
	private String roomtypePhoto;
	private Boolean roomtypeIssmoking;
	private String roomtypeComment;
	private Set roomtypeparamterses = new HashSet(0);
	private Set rooms = new HashSet(0);

	public Roomtype() {
	}

	public Roomtype(String roomtypeId) {
		this.roomtypeId = roomtypeId;
	}

	public Roomtype(String roomtypeId, Hotel hotel, String roomtypeName,
			String roomtypeTemplate, Integer roomtypeMinguests,
			Integer roomtypeMaxguests, String roomtypePhoto,
			Boolean roomtypeIssmoking, String roomtypeComment,
			Set roomtypeparamterses, Set rooms) {
		this.roomtypeId = roomtypeId;
		this.hotel = hotel;
		this.roomtypeName = roomtypeName;
		this.roomtypeTemplate = roomtypeTemplate;
		this.roomtypeMinguests = roomtypeMinguests;
		this.roomtypeMaxguests = roomtypeMaxguests;
		this.roomtypePhoto = roomtypePhoto;
		this.roomtypeIssmoking = roomtypeIssmoking;
		this.roomtypeComment = roomtypeComment;
		this.roomtypeparamterses = roomtypeparamterses;
		this.rooms = rooms;
	}

	public String getRoomtypeId() {
		return this.roomtypeId;
	}

	public void setRoomtypeId(String roomtypeId) {
		this.roomtypeId = roomtypeId;
	}

	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	public String getRoomtypeName() {
		return this.roomtypeName;
	}

	public void setRoomtypeName(String roomtypeName) {
		this.roomtypeName = roomtypeName;
	}

	public String getRoomtypeTemplate() {
		return this.roomtypeTemplate;
	}

	public void setRoomtypeTemplate(String roomtypeTemplate) {
		this.roomtypeTemplate = roomtypeTemplate;
	}

	public Integer getRoomtypeMinguests() {
		return this.roomtypeMinguests;
	}

	public void setRoomtypeMinguests(Integer roomtypeMinguests) {
		this.roomtypeMinguests = roomtypeMinguests;
	}

	public Integer getRoomtypeMaxguests() {
		return this.roomtypeMaxguests;
	}

	public void setRoomtypeMaxguests(Integer roomtypeMaxguests) {
		this.roomtypeMaxguests = roomtypeMaxguests;
	}

	public String getRoomtypePhoto() {
		return this.roomtypePhoto;
	}

	public void setRoomtypePhoto(String roomtypePhoto) {
		this.roomtypePhoto = roomtypePhoto;
	}

	public Boolean getRoomtypeIssmoking() {
		return this.roomtypeIssmoking;
	}

	public void setRoomtypeIssmoking(Boolean roomtypeIssmoking) {
		this.roomtypeIssmoking = roomtypeIssmoking;
	}

	public String getRoomtypeComment() {
		return this.roomtypeComment;
	}

	public void setRoomtypeComment(String roomtypeComment) {
		this.roomtypeComment = roomtypeComment;
	}

	public Set getRoomtypeparamterses() {
		return this.roomtypeparamterses;
	}

	public void setRoomtypeparamterses(Set roomtypeparamterses) {
		this.roomtypeparamterses = roomtypeparamterses;
	}

	public Set getRooms() {
		return this.rooms;
	}

	public void setRooms(Set rooms) {
		this.rooms = rooms;
	}

}
