INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AD','Andorra',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AE','United Arab Emirates',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AF','Afghanista',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AG','Antigua and Barbuda',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AI','Anguilla',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AL','Albania',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AM','Armenia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','A','Netherlands Antilles',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AO','Angola',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AQ','Antarctica',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AR','Argentina',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AS','American Samoa',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AT','Austria',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AU','Australia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AW','Aruba',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','AZ','Azerbaija',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BA','Bosnia and Herzegovina',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BB','Barbados',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BD','Bangladesh',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BE','Belgium',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BF','Burkina Faso',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BG','Bulgaria',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BH','Bahrai',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BI','Burundi',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BJ','Beni',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BM','Bermuda',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','B','Brunei Darussalam',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BO','Bolivia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BR','Brazil',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BS','Bahamas',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BT','Bhuta',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BV','Bouvet Island',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BW','Botswana',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BY','Belarus',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','BZ','Belize',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CA','Canada',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CC','Cocos',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CF','Central African Republic',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CG','Congo',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CH','Switzerland',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CI','Ivory Coast',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CK','Cook Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CL','Chile',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CM','Cameroo',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','C','China',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CO','Colombia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CR','Costa Rica',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CU','Cuba',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CV','Cape Verde',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CX','Christmas Island',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CY','Cyprus',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','CZ','Czech Republic',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','DE','Germany',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','DJ','Djibouti',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','DK','Denmark',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','DM','Dominica',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','DO','Dominican Republic',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','DZ','Algeria',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','EC','Ecuador',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','EE','Estonia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','EG','Egypt',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','EH','Western Sahara',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','ER','Eritrea',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','ES','Spai',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','ET','Ethiopia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','FI','Finland',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','FJ','Fiji',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','FK','Falkland Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','FM','Micronesia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','FO','Faroe Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','FR','France',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GA','Gabo',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GD','Grenada',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GE','Georgia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GF','French Guiana',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GH','Ghana',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GI','Gibraltar',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GL','Greenland',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GM','Gambia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','G','Guinea',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GP','Guadeloupe',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GQ','Equatorial Guinea',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GR','Greece',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GS','S. Georgia and S. Sandwich Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GT','Guatemala',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GU','Guam',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GW','Guinea-Bissau',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GY','Guyana',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','HK','Hong Kong',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','HM','Heard and McDonald Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','H','Honduras',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','HR','Croatia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','HT','Haiti',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','HU','Hungary',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','ID','Indonesia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','IE','Ireland',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','IL','Israel',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','I','India',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','IO','British Indian Ocean Territory',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','IQ','Iraq',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','IR','Ira',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','IS','Iceland',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','IT','Italy',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','JM','Jamaica',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','JO','Jorda',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','JP','Japa',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','KE','Kenya',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','KG','Kyrgyzsta',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','KH','Cambodia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','KI','Kiribati',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','KM','Comoros',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','K','Saint Kitts and Nevis',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','KP','North Korea',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','KR','South Korea',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','KW','Kuwait',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','KY','Cayman Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','KZ','Kazakhsta',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','LA','Laos',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','LB','Lebano',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','LC','Saint Lucia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','LI','Liechtenstei',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','LK','Sri Lanka',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','LR','Liberia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','LS','Lesotho',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','LT','Lithuania',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','LU','Luxembourg',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','LV','Latvia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','LY','Libya',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MA','Morocco',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MC','Monaco',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MD','Moldova',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MG','Madagascar',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MH','Marshall Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MK','Macedonia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','ML','Mali',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MM','Myanmar',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','M','Mongolia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MO','Macau',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MP','Northern Mariana Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MQ','Martinique',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MR','Mauritania',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MS','Montserrat',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MT','Malta',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MU','Mauritius',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MV','Maldives',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MW','Malawi',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MX','Mexico',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MY','Malaysia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','MZ','Mozambique',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','NA','Namibia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','NC','New Caledonia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','NE','Niger',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','NF','Norfolk Island',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','NG','Nigeria',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','NI','Nicaragua',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','NL','Netherlands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','NO','Norway',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','NP','Nepal',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','NR','Nauru',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','NU','Niue',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','NZ','New Zealand',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','OM','Oma',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','PA','Panama',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','PE','Peru',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','PF','French Polynesia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','PG','Papua New Guinea',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','PH','Philippines',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','PK','Pakista',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','PL','Poland',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','PM','St. Pierre and Miquelo',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','P','Pitcair',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','PR','Puerto Rico',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','PT','Portugal',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','PW','Palau',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','PY','Paraguay',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','QA','Qatar',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','RE','Reunio',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','RO','Romania',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','RU','Russian Federatio',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','RW','Rwanda',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SA','Saudi Arabia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SB','Solomon Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SC','Seychelles',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SD','Suda',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SE','Swede',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SG','Singapore',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SH','St. Helena',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SI','Slovenia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SJ','Svalbard and Jan Mayen Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SK','Slovakia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SL','Sierra Leone',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SM','San Marino',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','S','Senegal',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SO','Somalia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SR','Suriname',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','ST','Sao Tome and Principe',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SU','Soviet Unio',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SV','El Salvador',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SY','Syria',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','SZ','Swaziland',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TC','Turks and Caicos Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TD','Chad',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TF','French Southern Territories',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TG','Togo',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TH','Thailand',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TJ','Tajikista',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TK','Tokelau',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TM','Turkmenista',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','T','Tunisia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TO','Tonga',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TP','East Timor',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TR','Turkey',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TT','Trinidad and Tobago',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TV','Tuvalu',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TW','Taiwa',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','TZ','Tanzania',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','UA','Ukraine',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','UG','Uganda',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','GB','United Kingdom',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','UM','US Minor Outlying Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','US','United States',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','UY','Uruguay',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','UZ','Uzbekista',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','VC','Saint Vincent and The Grenadines',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','VE','Venezuela',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','VG','British Virgin Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','VI','US Virgin Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','V','Viet Nam',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','VU','Vanuatu',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','WF','Wallis and Futuna Islands',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','WS','Samoa',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','YE','Yeme',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','YT','Mayotte',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','YU','Yugoslavia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','ZA','South Africa',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','ZM','Zambia',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','ZR','Zaire',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Country','ZW','Zimbabwe',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Currency','CAD','Canadian Dollars (CAD)',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Currency','EUR','Euros (EUR)',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Currency','GBP','Pounds Sterling (GBP)',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Currency','JPY','Yen (JPY)',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Currency','USD','U.S. Dollars (USD)',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Currency','CNY','CNY 中国元(人民币)',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Frequency','D','Day(s)',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Frequency','M','Month(s)',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Frequency','','None',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Frequency','O','One-time Fee',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Frequency','W','Week(s)',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Frequency','Y','Year(s)',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Site Log Reports','1','Page Views By Day',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Site Log Reports','2','Detailed Site Log',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Site Log Reports','3','User Frequency',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Site Log Reports','4','Site Referrals',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Site Log Reports','5','User Agents',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Site Log Reports','6','Page Views By Hour',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Site Log Reports','7','Page Views By Day Of Week',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Site Log Reports','8','Page Views By Month',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Site Log Reports','9','Page Popularity',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Site Log Reports','10','User Registrations By Date',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Site Log Reports','11','User Registrations By Country',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Site Log Reports','12','Affiliate Referrals',NULL,0,0,-1,NULL);

/*-- language --*/
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Language','zh_CN','简体,中文,zh-cn(默认)',NULL,0,1,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Language','us_EN','United States,English,us-en',NULL,0,2,-1,NULL);
/*-- timeZone --*/
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','-720','(UTC -12:00) 国际日期变更线西',NULL,0,1,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','-660','(UTC -11:00) 协调世界时-11',NULL,0,2,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','-600','(UTC -10:00) Hawaii',NULL,0,3,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','-540','(UTC -09:00) Alaska',NULL,0,4,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','-480','(UTC -08:00) Pacific Time (US Canada); Tijuana',NULL,0,5,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','-420','(UTC -07:00) Mountain Time (US Canada)',NULL,0,6,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','-360','(UTC -06:00) Central Time (US Canada)',NULL,0,7,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','-300','(UTC -05:00) Eastern Time (US Canada)',NULL,0,8,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','-240','(UTC -04:00) Atlantic Time (Canada)',NULL,0,9,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','-210','(UTC -03:30) NewfoundLand Time(Canada)',NULL,0,10,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','-180','(UTC -03:00) Buenos Aires,Georgetown',NULL,0,11,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','-120','(UTC -02:00) Mid-Atlantic',NULL,0,12,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','-60','(UTC -01:00) Cape Verde Is.',NULL,0,13,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','0','(UTC 00:00) Dublin, Edinburgh, Lisbon,London',NULL,0,14,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','60','(UTC +01:00) Amsterdam, Berlin, Bern,Rome, Paris, Stockholm, Vienna',NULL,0,15,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','120','(UTC +02:00) Athens, Bucharest,Istanbul, Minsk',NULL,0,16,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','180','(UTC +03:00) Moscow, St. Petersburg,Volgograd',NULL,0,17,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','210','(UTC +03:30) Tehran',NULL,0,18,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','240','(UTC +04:00) Abu Dhabi, Muscat',NULL,0,19,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','270','(UTC +04:30) Kabul',NULL,0,20,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','300','(UTC +05:00) Islamabad, Karachi,Tashkent',NULL,0,0,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','330','(UTC +05:30) Calcutta, Chennai,Mumbai,New Delhi',NULL,0,21,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','345','(UTC +05:45) Kathmandu',NULL,0,22,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','360','(UTC +06:00) Astana,Almaty, Dhaka,Novosibirsk',NULL,0,23,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','390','(UTC +06:30) Rangoon (Yangon, Burma)',NULL,0,24,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','420','(UTC +07:00) Bangkok, Hanoi, Jakarta',NULL,0,25,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','480','(UTC +08:00) 北京, 重庆, 香港特别行政区, 乌鲁木齐',NULL,0,26,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','540','(UTC +09:00) Osaka, Sapporo, Tokyo',NULL,0,27,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','570','(UTC +09:30) Adelaide, Darwin',NULL,0,28,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','600','(UTC +10:00) Canberra, Melbourne,Sydney, Vladvostok',NULL,0,29,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','660','(UTC +11:00) Magadan, Solomon Is.,New Caledonia',NULL,0,30,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','720','(UTC +12:00) Auckland, Fiji,Kamchatka, Marshall Is.',NULL,0,31,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'TimeZone','780','(UTC +13:00) Nuku alofa',NULL,0,32,-1,NULL);

/*-- season --*/
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Season','winter','冬季',NULL,0,1,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Season','summer','夏季',NULL,0,2,-1,NULL);

/*-- Service Request --*/
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Service Request','sos','SOS紧急事件',NULL,0,1,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Service Request','dooralarm','门磁报警',NULL,0,2,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Service Request','windowalarm','窗磁报警',NULL,0,3,-1,NULL);

/*-- Local Data Synchronize Cycle --*/
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Local Data Synchronize Cycle','10','10-15s',NULL,0,1,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Local Data Synchronize Cycle','15','15-20s',NULL,0,2,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Local Data Synchronize Cycle','20','20-30s',NULL,0,3,-1,NULL);

/*-- Show Keyword Number --*/
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Show Keyword Number','4','4',NULL,0,1,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Show Keyword Number','5','5',NULL,0,2,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Show Keyword Number','6','6',NULL,0,3,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Show Keyword Number','7','7',NULL,0,4,-1,NULL);
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Show Keyword Number','8','8',NULL,0,5,-1,NULL);


/*-- Music --*/
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description) values (uuid(),'Music','beep','beep(Default)',NULL,0,1,-1,NULL);


/**-- Contact Phone --*/
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'Phone','mobilePhone','手机',NULL,0,1,-1,NULL,'zh_CN');
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'Phone','mobile2Phone','手机(2)',NULL,0,2,-1,NULL,'zh_CN');
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'Phone','homePhone','住宅电话',NULL,0,3,-1,NULL,'zh_CN');
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'Phone','home2Phone','住宅电话(2)',NULL,0,4,-1,NULL,'zh_CN');
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'Phone','workPhone','工作电话',NULL,0,5,-1,NULL,'zh_CN');
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'Phone','work2Phone','工作电话(2)',NULL,0,6,-1,NULL,'zh_CN');
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'Phone','otherPhone','其它',NULL,0,7,-1,NULL,'zh_CN');
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'Phone','companyPhone','公司',NULL,0,8,-1,NULL,'zh_CN');
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'Phone','workFax','公司传真',NULL,0,9,-1,NULL,'zh_CN');
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'Phone','homeFax','住宅传真',NULL,0,10,-1,NULL,'zh_CN');
/**-- Contact Address --*/
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'Address','workAddress','工作地址',NULL,0,1,-1,NULL,'zh_CN');
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'Address','homeAddress','住宅地址',NULL,0,2,-1,NULL,'zh_CN');
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'Address','homePhone','其他',NULL,0,3,-1,NULL,'zh_CN');
/**-- Contact Email Address --*/
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'EmaillAddress','personalEmail','个人',NULL,0,1,-1,NULL,'zh_CN');
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'EmaillAddress','workEmail','工作电子邮件',NULL,0,2,-1,NULL,'zh_CN');
INSERT INTO listinfo (entryid,ListName,Value,Text,ParentID,Level,SortOrder,DefinitionID,Description,langcode) values (uuid(),'EmaillAddress','otherEmail','其他',NULL,0,3,-1,NULL,'zh_CN');

