--本脚本用于。
--中文环境使用，部分货币代码重复。

--实际执行
truncate table currency;
Insert into CURRENCY (CURRENCYCODE,DESCRIPTION,ACTIVE,CHANGEDATE,CHANGEBY,CURRENCYID,LANGCODE,HASLD) values ('CNY','人民币',0,to_date('1-JAN-11','DD-MON-RR'),'MAXADMIN',CURRENCYSEQ.NEXTVAL,'ZH',0);
Insert into CURRENCY (CURRENCYCODE,DESCRIPTION,ACTIVE,CHANGEDATE,CHANGEBY,CURRENCYID,LANGCODE,HASLD) values ('USD','美元',0,to_date('1-JAN-11','DD-MON-RR'),'MAXADMIN',CURRENCYSEQ.NEXTVAL,'ZH',0);
Insert into CURRENCY (CURRENCYCODE,DESCRIPTION,ACTIVE,CHANGEDATE,CHANGEBY,CURRENCYID,LANGCODE,HASLD) values ('HKD','港币',0,to_date('1-JAN-11','DD-MON-RR'),'MAXADMIN',CURRENCYSEQ.NEXTVAL,'ZH',0);
Insert into CURRENCY (CURRENCYCODE,DESCRIPTION,ACTIVE,CHANGEDATE,CHANGEBY,CURRENCYID,LANGCODE,HASLD) values ('JPY','日圆',0,to_date('1-JAN-11','DD-MON-RR'),'MAXADMIN',CURRENCYSEQ.NEXTVAL,'ZH',0);
Insert into CURRENCY (CURRENCYCODE,DESCRIPTION,ACTIVE,CHANGEDATE,CHANGEBY,CURRENCYID,LANGCODE,HASLD) values ('EUR','欧元',0,to_date('1-JAN-11','DD-MON-RR'),'MAXADMIN',CURRENCYSEQ.NEXTVAL,'ZH',0);
Insert into CURRENCY (CURRENCYCODE,DESCRIPTION,ACTIVE,CHANGEDATE,CHANGEBY,CURRENCYID,LANGCODE,HASLD) values ('GBP','英镑',0,to_date('1-JAN-11','DD-MON-RR'),'MAXADMIN',CURRENCYSEQ.NEXTVAL,'ZH',0);
Insert into CURRENCY (CURRENCYCODE,DESCRIPTION,ACTIVE,CHANGEDATE,CHANGEBY,CURRENCYID,LANGCODE,HASLD) values ('DEM','德国马克',0,to_date('1-JAN-11','DD-MON-RR'),'MAXADMIN',CURRENCYSEQ.NEXTVAL,'ZH',0);
Insert into CURRENCY (CURRENCYCODE,DESCRIPTION,ACTIVE,CHANGEDATE,CHANGEBY,CURRENCYID,LANGCODE,HASLD) values ('FRF','法国法郎',0,to_date('1-JAN-11','DD-MON-RR'),'MAXADMIN',CURRENCYSEQ.NEXTVAL,'ZH',0);
Insert into CURRENCY (CURRENCYCODE,DESCRIPTION,ACTIVE,CHANGEDATE,CHANGEBY,CURRENCYID,LANGCODE,HASLD) values ('INR','印度卢比',0,to_date('1-JAN-11','DD-MON-RR'),'MAXADMIN',CURRENCYSEQ.NEXTVAL,'ZH',0);
Insert into CURRENCY (CURRENCYCODE,DESCRIPTION,ACTIVE,CHANGEDATE,CHANGEBY,CURRENCYID,LANGCODE,HASLD) values ('ESP','西班牙彼萨塔',0,to_date('1-JAN-11','DD-MON-RR'),'MAXADMIN',CURRENCYSEQ.NEXTVAL,'ZH',0);
Insert into CURRENCY (CURRENCYCODE,DESCRIPTION,ACTIVE,CHANGEDATE,CHANGEBY,CURRENCYID,LANGCODE,HASLD) values ('KRW','韩币',0,to_date('1-JAN-11','DD-MON-RR'),'MAXADMIN',CURRENCYSEQ.NEXTVAL,'ZH',0);
Insert into CURRENCY (CURRENCYCODE,DESCRIPTION,ACTIVE,CHANGEDATE,CHANGEBY,CURRENCYID,LANGCODE,HASLD) values ('KPW','朝鲜元',0,to_date('1-JAN-11','DD-MON-RR'),'MAXADMIN',CURRENCYSEQ.NEXTVAL,'ZH',0);
update CURRENCY set ACTIVE=1 where CURRENCYCODE in ('CNY','USD');
commit;

select * from currency;