package com.managementsystem.guestroom.domain.hibernate;

// Generated 2012-11-6 13:37:38 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private String deptId;
	private Department department;
	private Hotel hotel;
	private String deptCode;
	private String deptShortname;
	private String deptName;
	private Integer priority;
	private String deptManager;
	private String deptPhoto;
	private String deptFax;
	private String deptComment;
	private Set departments = new HashSet(0);

	public Department() {
	}

	public Department(String deptId) {
		this.deptId = deptId;
	}

	public Department(String deptId, Department department, Hotel hotel,
			String deptCode, String deptShortname, String deptName,
			Integer priority, String deptManager, String deptPhoto,
			String deptFax, String deptComment, Set departments) {
		this.deptId = deptId;
		this.department = department;
		this.hotel = hotel;
		this.deptCode = deptCode;
		this.deptShortname = deptShortname;
		this.deptName = deptName;
		this.priority = priority;
		this.deptManager = deptManager;
		this.deptPhoto = deptPhoto;
		this.deptFax = deptFax;
		this.deptComment = deptComment;
		this.departments = departments;
	}

	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	public String getDeptCode() {
		return this.deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public String getDeptShortname() {
		return this.deptShortname;
	}

	public void setDeptShortname(String deptShortname) {
		this.deptShortname = deptShortname;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public String getDeptManager() {
		return this.deptManager;
	}

	public void setDeptManager(String deptManager) {
		this.deptManager = deptManager;
	}

	public String getDeptPhoto() {
		return this.deptPhoto;
	}

	public void setDeptPhoto(String deptPhoto) {
		this.deptPhoto = deptPhoto;
	}

	public String getDeptFax() {
		return this.deptFax;
	}

	public void setDeptFax(String deptFax) {
		this.deptFax = deptFax;
	}

	public String getDeptComment() {
		return this.deptComment;
	}

	public void setDeptComment(String deptComment) {
		this.deptComment = deptComment;
	}

	public Set getDepartments() {
		return this.departments;
	}

	public void setDepartments(Set departments) {
		this.departments = departments;
	}

}
