package com.managementsystem.guestroom.domain.hibernate;

// Generated 2012-11-6 13:37:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Eventlog generated by hbm2java
 */
public class Eventlog implements java.io.Serializable {

	private String logUuid;
	private Eventlogtype eventlogtype;
	private String userId;
	private String userName;
	private Date logCreatedate;
	private String logServername;
	private String logProperties;
	private Boolean logNotificationpending;

	public Eventlog() {
	}

	public Eventlog(String logUuid) {
		this.logUuid = logUuid;
	}

	public Eventlog(String logUuid, Eventlogtype eventlogtype, String userId,
			String userName, Date logCreatedate, String logServername,
			String logProperties, Boolean logNotificationpending) {
		this.logUuid = logUuid;
		this.eventlogtype = eventlogtype;
		this.userId = userId;
		this.userName = userName;
		this.logCreatedate = logCreatedate;
		this.logServername = logServername;
		this.logProperties = logProperties;
		this.logNotificationpending = logNotificationpending;
	}

	public String getLogUuid() {
		return this.logUuid;
	}

	public void setLogUuid(String logUuid) {
		this.logUuid = logUuid;
	}

	public Eventlogtype getEventlogtype() {
		return this.eventlogtype;
	}

	public void setEventlogtype(Eventlogtype eventlogtype) {
		this.eventlogtype = eventlogtype;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Date getLogCreatedate() {
		return this.logCreatedate;
	}

	public void setLogCreatedate(Date logCreatedate) {
		this.logCreatedate = logCreatedate;
	}

	public String getLogServername() {
		return this.logServername;
	}

	public void setLogServername(String logServername) {
		this.logServername = logServername;
	}

	public String getLogProperties() {
		return this.logProperties;
	}

	public void setLogProperties(String logProperties) {
		this.logProperties = logProperties;
	}

	public Boolean getLogNotificationpending() {
		return this.logNotificationpending;
	}

	public void setLogNotificationpending(Boolean logNotificationpending) {
		this.logNotificationpending = logNotificationpending;
	}

}
