package com.managementsystem.guestroom.domain.hibernate;

// Generated 2012-11-6 13:37:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Guest generated by hbm2java
 */
public class Guest implements java.io.Serializable {

	private String guestId;
	private String profileid;
	private String profiletype;
	private String lanaguage;
	private String currency;
	private Date createdondate;
	private Date firststay;
	private Date laststay;
	private String firstname;
	private String lastname;
	private String salutation;
	private String roomNo;
	private String gender;
	private Boolean inactive;
	private String company;
	private String address;
	private String country;
	private String state;
	private String city;
	private String zip;
	private String phoneHome;
	private String fax;
	private String phoneMobile;
	private String phoneBus;
	private String phoneBusext;
	private String phoneOther;
	private String email;
	private String url;
	private Boolean isprompt;
	private String comment;
	private Set guestpreferences = new HashSet(0);

	public Guest() {
	}

	public Guest(String guestId) {
		this.guestId = guestId;
	}

	public Guest(String guestId, String profileid, String profiletype,
			String lanaguage, String currency, Date createdondate,
			Date firststay, Date laststay, String firstname, String lastname,
			String salutation, String roomNo, String gender, Boolean inactive,
			String company, String address, String country, String state,
			String city, String zip, String phoneHome, String fax,
			String phoneMobile, String phoneBus, String phoneBusext,
			String phoneOther, String email, String url, Boolean isprompt,
			String comment, Set guestpreferences) {
		this.guestId = guestId;
		this.profileid = profileid;
		this.profiletype = profiletype;
		this.lanaguage = lanaguage;
		this.currency = currency;
		this.createdondate = createdondate;
		this.firststay = firststay;
		this.laststay = laststay;
		this.firstname = firstname;
		this.lastname = lastname;
		this.salutation = salutation;
		this.roomNo = roomNo;
		this.gender = gender;
		this.inactive = inactive;
		this.company = company;
		this.address = address;
		this.country = country;
		this.state = state;
		this.city = city;
		this.zip = zip;
		this.phoneHome = phoneHome;
		this.fax = fax;
		this.phoneMobile = phoneMobile;
		this.phoneBus = phoneBus;
		this.phoneBusext = phoneBusext;
		this.phoneOther = phoneOther;
		this.email = email;
		this.url = url;
		this.isprompt = isprompt;
		this.comment = comment;
		this.guestpreferences = guestpreferences;
	}

	public String getGuestId() {
		return this.guestId;
	}

	public void setGuestId(String guestId) {
		this.guestId = guestId;
	}

	public String getProfileid() {
		return this.profileid;
	}

	public void setProfileid(String profileid) {
		this.profileid = profileid;
	}

	public String getProfiletype() {
		return this.profiletype;
	}

	public void setProfiletype(String profiletype) {
		this.profiletype = profiletype;
	}

	public String getLanaguage() {
		return this.lanaguage;
	}

	public void setLanaguage(String lanaguage) {
		this.lanaguage = lanaguage;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public Date getCreatedondate() {
		return this.createdondate;
	}

	public void setCreatedondate(Date createdondate) {
		this.createdondate = createdondate;
	}

	public Date getFirststay() {
		return this.firststay;
	}

	public void setFirststay(Date firststay) {
		this.firststay = firststay;
	}

	public Date getLaststay() {
		return this.laststay;
	}

	public void setLaststay(Date laststay) {
		this.laststay = laststay;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	public String getRoomNo() {
		return this.roomNo;
	}

	public void setRoomNo(String roomNo) {
		this.roomNo = roomNo;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Boolean getInactive() {
		return this.inactive;
	}

	public void setInactive(Boolean inactive) {
		this.inactive = inactive;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getPhoneHome() {
		return this.phoneHome;
	}

	public void setPhoneHome(String phoneHome) {
		this.phoneHome = phoneHome;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getPhoneMobile() {
		return this.phoneMobile;
	}

	public void setPhoneMobile(String phoneMobile) {
		this.phoneMobile = phoneMobile;
	}

	public String getPhoneBus() {
		return this.phoneBus;
	}

	public void setPhoneBus(String phoneBus) {
		this.phoneBus = phoneBus;
	}

	public String getPhoneBusext() {
		return this.phoneBusext;
	}

	public void setPhoneBusext(String phoneBusext) {
		this.phoneBusext = phoneBusext;
	}

	public String getPhoneOther() {
		return this.phoneOther;
	}

	public void setPhoneOther(String phoneOther) {
		this.phoneOther = phoneOther;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Boolean getIsprompt() {
		return this.isprompt;
	}

	public void setIsprompt(Boolean isprompt) {
		this.isprompt = isprompt;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Set getGuestpreferences() {
		return this.guestpreferences;
	}

	public void setGuestpreferences(Set guestpreferences) {
		this.guestpreferences = guestpreferences;
	}

}
