package com.managementsystem.guestroom.domain.hibernate;

// Generated 2012-11-5 14:40:23 by Hibernate Tools 3.4.0.CR1

/**
 * GuestpreferenceId generated by hbm2java
 */
public class GuestpreferenceId implements java.io.Serializable {

	private String guestId;
	private String definedfieldid;

	public GuestpreferenceId() {
	}

	public GuestpreferenceId(String guestId, String definedfieldid) {
		this.guestId = guestId;
		this.definedfieldid = definedfieldid;
	}

	public String getGuestId() {
		return this.guestId;
	}

	public void setGuestId(String guestId) {
		this.guestId = guestId;
	}

	public String getDefinedfieldid() {
		return this.definedfieldid;
	}

	public void setDefinedfieldid(String definedfieldid) {
		this.definedfieldid = definedfieldid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GuestpreferenceId))
			return false;
		GuestpreferenceId castOther = (GuestpreferenceId) other;

		return ((this.getGuestId() == castOther.getGuestId()) || (this
				.getGuestId() != null && castOther.getGuestId() != null && this
				.getGuestId().equals(castOther.getGuestId())))
				&& ((this.getDefinedfieldid() == castOther.getDefinedfieldid()) || (this
						.getDefinedfieldid() != null
						&& castOther.getDefinedfieldid() != null && this
						.getDefinedfieldid().equals(
								castOther.getDefinedfieldid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGuestId() == null ? 0 : this.getGuestId().hashCode());
		result = 37
				* result
				+ (getDefinedfieldid() == null ? 0 : this.getDefinedfieldid()
						.hashCode());
		return result;
	}

}
