package com.managementsystem.guestroom.domain.hibernate;

// Generated 2012-11-5 14:40:23 by Hibernate Tools 3.4.0.CR1

/**
 * Guestpreference generated by hbm2java
 */
public class Guestpreference implements java.io.Serializable {

	private GuestpreferenceId id;
	private Guest guest;
	private Prefsdefinedfield prefsdefinedfield;
	private String prefsValue;

	public Guestpreference() {
	}

	public Guestpreference(GuestpreferenceId id, Guest guest,
			Prefsdefinedfield prefsdefinedfield) {
		this.id = id;
		this.guest = guest;
		this.prefsdefinedfield = prefsdefinedfield;
	}

	public Guestpreference(GuestpreferenceId id, Guest guest,
			Prefsdefinedfield prefsdefinedfield, String prefsValue) {
		this.id = id;
		this.guest = guest;
		this.prefsdefinedfield = prefsdefinedfield;
		this.prefsValue = prefsValue;
	}

	public GuestpreferenceId getId() {
		return this.id;
	}

	public void setId(GuestpreferenceId id) {
		this.id = id;
	}

	public Guest getGuest() {
		return this.guest;
	}

	public void setGuest(Guest guest) {
		this.guest = guest;
	}

	public Prefsdefinedfield getPrefsdefinedfield() {
		return this.prefsdefinedfield;
	}

	public void setPrefsdefinedfield(Prefsdefinedfield prefsdefinedfield) {
		this.prefsdefinedfield = prefsdefinedfield;
	}

	public String getPrefsValue() {
		return this.prefsValue;
	}

	public void setPrefsValue(String prefsValue) {
		this.prefsValue = prefsValue;
	}

}
