package com.managementsystem.guestroom.domain.hibernate;

// Generated 2012-11-5 14:40:23 by Hibernate Tools 3.4.0.CR1

/**
 * Roomtypeparamters generated by hbm2java
 */
public class Roomtypeparamters implements java.io.Serializable {

	private String paramterId;
	private Roomtype roomtype;
	private String paramterKey;
	private String paramterName;
	private String paramterComment;
	private String paramterLocation;

	public Roomtypeparamters() {
	}

	public Roomtypeparamters(String paramterId) {
		this.paramterId = paramterId;
	}

	public Roomtypeparamters(String paramterId, Roomtype roomtype,
			String paramterKey, String paramterName, String paramterComment,
			String paramterLocation) {
		this.paramterId = paramterId;
		this.roomtype = roomtype;
		this.paramterKey = paramterKey;
		this.paramterName = paramterName;
		this.paramterComment = paramterComment;
		this.paramterLocation = paramterLocation;
	}

	public String getParamterId() {
		return this.paramterId;
	}

	public void setParamterId(String paramterId) {
		this.paramterId = paramterId;
	}

	public Roomtype getRoomtype() {
		return this.roomtype;
	}

	public void setRoomtype(Roomtype roomtype) {
		this.roomtype = roomtype;
	}

	public String getParamterKey() {
		return this.paramterKey;
	}

	public void setParamterKey(String paramterKey) {
		this.paramterKey = paramterKey;
	}

	public String getParamterName() {
		return this.paramterName;
	}

	public void setParamterName(String paramterName) {
		this.paramterName = paramterName;
	}

	public String getParamterComment() {
		return this.paramterComment;
	}

	public void setParamterComment(String paramterComment) {
		this.paramterComment = paramterComment;
	}

	public String getParamterLocation() {
		return this.paramterLocation;
	}

	public void setParamterLocation(String paramterLocation) {
		this.paramterLocation = paramterLocation;
	}

}
