package com.managementsystem.guestroom.domain.hibernate;

// Generated 2012-11-5 14:40:23 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Roomgroup generated by hbm2java
 */
public class Roomgroup implements java.io.Serializable {

	private String roomgroupId;
	private String roomgroupName;
	private String roomgroupDesc;
	private Set roomassignedgrouieses = new HashSet(0);

	public Roomgroup() {
	}

	public Roomgroup(String roomgroupId) {
		this.roomgroupId = roomgroupId;
	}

	public Roomgroup(String roomgroupId, String roomgroupName,
			String roomgroupDesc, Set roomassignedgrouieses) {
		this.roomgroupId = roomgroupId;
		this.roomgroupName = roomgroupName;
		this.roomgroupDesc = roomgroupDesc;
		this.roomassignedgrouieses = roomassignedgrouieses;
	}

	public String getRoomgroupId() {
		return this.roomgroupId;
	}

	public void setRoomgroupId(String roomgroupId) {
		this.roomgroupId = roomgroupId;
	}

	public String getRoomgroupName() {
		return this.roomgroupName;
	}

	public void setRoomgroupName(String roomgroupName) {
		this.roomgroupName = roomgroupName;
	}

	public String getRoomgroupDesc() {
		return this.roomgroupDesc;
	}

	public void setRoomgroupDesc(String roomgroupDesc) {
		this.roomgroupDesc = roomgroupDesc;
	}

	public Set getRoomassignedgrouieses() {
		return this.roomassignedgrouieses;
	}

	public void setRoomassignedgrouieses(Set roomassignedgrouieses) {
		this.roomassignedgrouieses = roomassignedgrouieses;
	}

}
