package com.managementsystem.guestroom.domain.hibernate;

// Generated 2012-11-5 14:40:23 by Hibernate Tools 3.4.0.CR1

/**
 * Roomconfig generated by hbm2java
 */
public class Roomconfig implements java.io.Serializable {

	private String roomNo;
	private Room room;
	private String roomIp;
	private Integer roomPort;

	public Roomconfig() {
	}

	public Roomconfig(Room room) {
		this.room = room;
	}

	public Roomconfig(Room room, String roomIp, Integer roomPort) {
		this.room = room;
		this.roomIp = roomIp;
		this.roomPort = roomPort;
	}

	public String getRoomNo() {
		return this.roomNo;
	}

	public void setRoomNo(String roomNo) {
		this.roomNo = roomNo;
	}

	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	public String getRoomIp() {
		return this.roomIp;
	}

	public void setRoomIp(String roomIp) {
		this.roomIp = roomIp;
	}

	public Integer getRoomPort() {
		return this.roomPort;
	}

	public void setRoomPort(Integer roomPort) {
		this.roomPort = roomPort;
	}

}
